import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Provider from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Gelianthus' Shed Sale",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en ">
			<head>
				<link
					rel="icon"
					href="/images/logo.webp"
					sizes="any"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
					rel="stylesheet"
				/>
			</head>
			<body className={`${inter.className} box-border`}>
				<Provider>
					{children}
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
